dist: xenial

language: java

jdk:
  - openjdk8

install:
  - chmod +x ./gradlew
  - echo "tbaKey=$tbaKey" > gradle.properties
  - cat gradle.properties
  - ./gradlew --version

script:
  - ./gradlew build --scan -s